import type { Template } from '@/contracts/template';

export const rawTemplates = [
  {
    slug: 'psicologo-clinico-agenda',
    title: 'Psicólogo clínico con agenda online',
    shortDescription:
      'Landing profesional para psicólogos con enfoque clínico, servicios, sobre mí, contacto, WhatsApp y reserva de entrevista.',
    longDescription:
      'Template basado en un sitio real para atención psicológica. Está pensado para profesionales de salud mental que necesitan transmitir confianza, explicar su enfoque de trabajo y facilitar una primera consulta o reserva de entrevista.',
    audience: ['psychology', 'health'],
    format: 'landing',
    stack: ['nextjs', 'tailwind', 'static_export'],
    tags: ['psicologia', 'salud', 'agenda', 'landing', 'servicios-profesionales'],
    bestFor:
      'Profesionales independientes que necesitan confianza, claridad y una vía directa a primera consulta.',
    primaryGoal: 'Convertir visitas en consultas o reservas de entrevista inicial.',
    complexity: 'simple',
    recommendedFor: [
      'Psicólogos, terapeutas y profesionales de salud mental con servicios definidos',
      'Consultorios que ya tienen datos de contacto, modalidad de atención y agenda',
      'Profesionales que buscan presencia online sobria sin vender múltiples productos',
    ],
    notIdealFor: [
      'Clínicas con muchas sedes, equipos grandes o necesidades de turnos complejos',
      'Marcas que todavía no definieron enfoque, servicios ni tono profesional',
    ],
    screenshot: '/templates/psicologo-clinico-agenda.png',
    demoUrl: 'https://maydana-psicologo.vercel.app/',
    price: {
      amountARS: 180000,
      currency: 'ARS',
      kind: 'from',
    },
    deliveryDays: {
      min: 5,
      max: 10,
    },
    includedSections: [
      'Hero con posicionamiento profesional',
      'Cuándo consultar',
      'Enfoque terapéutico',
      'Modalidades de trabajo',
      'Sobre mí / experiencia',
      'Contacto, WhatsApp y agenda',
    ],
    requiredInputs: [
      'Nombre profesional',
      'Matrícula o credenciales si corresponde',
      'Texto de presentación',
      'Modalidades de atención',
      'Servicios o problemáticas que aborda',
      'Email, WhatsApp y link de agenda',
      'Foto profesional o imágenes de apoyo',
    ],
    status: 'active',
    featured: true,
  },
  {
    slug: 'formacion-cursos-consultas',
    title: 'Formación, cursos y consultas profesionales',
    shortDescription:
      'Sitio institucional para profesionales que ofrecen cursos, talleres, análisis, divulgación y consultas por WhatsApp.',
    longDescription:
      'Template basado en un sitio real de grafología y neuroescritura. Sirve para profesionales o pequeños negocios que combinan formación, servicios de análisis, talleres, seminarios y contenidos de divulgación.',
    audience: ['education', 'consulting'],
    format: 'institutional',
    stack: ['nextjs', 'tailwind', 'static_export'],
    tags: ['educacion', 'cursos', 'talleres', 'consultoria', 'institucional'],
    bestFor:
      'Profesionales o pequeños equipos que combinan autoridad institucional, formación y consultas.',
    primaryGoal: 'Presentar cursos, talleres y servicios para generar consultas calificadas.',
    complexity: 'standard',
    recommendedFor: [
      'Consultores, docentes o especialistas con varias líneas de servicio',
      'Profesionales que ofrecen talleres, seminarios y consultas individuales',
      'Marcas que necesitan explicar una disciplina antes de recibir consultas',
    ],
    notIdealFor: [
      'Negocios que necesitan ecommerce, carrito o inscripción automática avanzada',
      'Proyectos con una sola oferta simple que funcionaría mejor como landing corta',
    ],
    screenshot: '/templates/formacion-cursos-consultas.png',
    demoUrl: 'https://grafoescrito.vercel.app/',
    price: {
      amountARS: 240000,
      currency: 'ARS',
      kind: 'from',
    },
    deliveryDays: {
      min: 7,
      max: 14,
    },
    includedSections: [
      'Hero institucional',
      'Presentación de disciplina o propuesta',
      'Áreas de trabajo',
      'Caminos de formación',
      'Talleres y seminarios',
      'Sobre el profesional',
      'Recursos o temas de divulgación',
      'Contacto por WhatsApp/email',
    ],
    requiredInputs: [
      'Nombre de marca o profesional',
      'Descripción de la actividad',
      'Cursos o servicios principales',
      'Talleres o seminarios disponibles',
      'Bio profesional',
      'Datos de contacto',
      'Fotos o imágenes de apoyo',
    ],
    status: 'active',
    featured: true,
  },
  {
    slug: 'abogado-estudio-profesional',
    title: 'Abogado o estudio profesional',
    shortDescription:
      'Sitio institucional para abogados y estudios jurídicos con áreas de práctica, perfil profesional, consulta inicial y contacto claro.',
    longDescription:
      'Template para abogados independientes o estudios pequeños que necesitan transmitir seriedad, explicar áreas de práctica y convertir visitas en consultas calificadas. Está pensado para una presencia sobria, clara y orientada a contacto, sin prometer resultados ni reemplazar asesoramiento legal personalizado.',
    audience: ['legal', 'consulting'],
    format: 'institutional',
    stack: ['nextjs', 'tailwind', 'static_export'],
    tags: ['legal', 'abogados', 'estudio-juridico', 'consultas', 'institucional'],
    bestFor:
      'Abogados o estudios pequeños con áreas de práctica definidas y necesidad de consultas calificadas.',
    primaryGoal: 'Presentar especialidades legales y convertir visitas en contactos de consulta.',
    complexity: 'standard',
    recommendedFor: [
      'Profesionales legales que quieren una presencia sobria y confiable',
      'Estudios con dos a cinco áreas de práctica principales',
      'Servicios que requieren explicar proceso, criterios y canales de consulta',
    ],
    notIdealFor: [
      'Portales legales con login, expedientes o gestión documental privada',
      'Estudios que necesitan publicar novedades legales con frecuencia de medio editorial',
    ],
    screenshot: '/templates/abogado-estudio-profesional.png',
    demoUrl: 'https://example.com/templates/abogado-estudio-profesional',
    price: {
      amountARS: 260000,
      currency: 'ARS',
      kind: 'from',
    },
    deliveryDays: {
      min: 7,
      max: 14,
    },
    includedSections: [
      'Hero institucional con especialidad principal',
      'Áreas de práctica o servicios legales',
      'Perfil del abogado o equipo',
      'Cómo funciona la consulta',
      'Preguntas frecuentes generales',
      'Contacto por WhatsApp/email',
      'Disclaimer legal básico',
    ],
    requiredInputs: [
      'Nombre del profesional o estudio',
      'Matrícula o credenciales públicas si corresponde',
      'Áreas de práctica principales',
      'Bio profesional o perfil del equipo',
      'Datos de contacto',
      'Textos legales o disclaimers requeridos',
      'Foto profesional o imagen institucional',
    ],
    status: 'active',
    featured: true,
  },
  {
    slug: 'odontologia-estetica-turnos',
    title: 'Odontología y estética dental',
    shortDescription:
      'Landing para odontólogos, consultorios dentales o estética dental con tratamientos, confianza profesional, ubicación y turnos.',
    longDescription:
      'Template orientado a odontólogos y consultorios dentales que necesitan convertir búsquedas locales o recomendaciones en turnos. Combina presentación profesional, tratamientos destacados, señales de confianza, fotos del espacio y CTA a consulta o reserva.',
    audience: ['health', 'local_business'],
    format: 'landing',
    stack: ['nextjs', 'tailwind', 'static_export'],
    tags: ['odontologia', 'salud', 'estetica-dental', 'turnos', 'local'],
    bestFor:
      'Consultorios odontológicos o profesionales de estética dental con servicios claros y canal de turnos existente.',
    primaryGoal: 'Convertir visitas en reservas de consulta odontológica o estética.',
    complexity: 'standard',
    recommendedFor: [
      'Odontólogos independientes con consultorio propio',
      'Consultorios con tratamientos destacados y ubicación física',
      'Profesionales que ya gestionan turnos por WhatsApp, teléfono o agenda externa',
    ],
    notIdealFor: [
      'Clínicas grandes con turnero nativo, múltiples sedes y portal de pacientes',
      'Servicios sin fotos, credenciales públicas o lista clara de tratamientos',
    ],
    screenshot: '/templates/odontologia-estetica-turnos.png',
    demoUrl: 'https://example.com/templates/odontologia-estetica-turnos',
    price: {
      amountARS: 300000,
      currency: 'ARS',
      kind: 'from',
    },
    deliveryDays: {
      min: 7,
      max: 14,
    },
    includedSections: [
      'Hero con tratamiento o propuesta principal',
      'Tratamientos destacados',
      'Diferenciales profesionales',
      'Fotos del consultorio o galería cuidada',
      'Cómo pedir turno',
      'Ubicación y horarios',
      'Preguntas frecuentes',
    ],
    requiredInputs: [
      'Nombre profesional o consultorio',
      'Matrícula o credenciales públicas',
      'Tratamientos ofrecidos',
      'Fotos del consultorio',
      'Imágenes antes/después si pueden usarse',
      'Dirección y horarios',
      'Canal de turnos',
    ],
    status: 'active',
    featured: true,
  },
  {
    slug: 'consultor-data-ai',
    title: 'Consultor de datos e IA',
    shortDescription:
      'Landing consultiva para especialistas en datos, automatización o IA con servicios, casos de uso y llamada a diagnóstico.',
    longDescription:
      'Template para consultores técnicos que necesitan traducir capacidades de datos, automatización o inteligencia artificial en valor de negocio. Ordena problemas, servicios, casos de uso y proceso de trabajo para llevar al visitante a una reunión de diagnóstico.',
    audience: ['consulting'],
    format: 'landing',
    stack: ['nextjs', 'tailwind', 'static_export'],
    tags: ['consultoria', 'datos', 'ia', 'automatizacion', 'b2b'],
    bestFor:
      'Consultores independientes o boutiques B2B que venden diagnóstico, automatización y estrategia de datos.',
    primaryGoal: 'Convertir interés técnico en reuniones de diagnóstico con contexto suficiente.',
    complexity: 'standard',
    recommendedFor: [
      'Consultores con servicios B2B claros y ejemplos de problemas que resuelven',
      'Especialistas que necesitan traducir tecnología a beneficios de negocio',
      'Ofertas de diagnóstico, roadmap, automatización o implementación liviana',
    ],
    notIdealFor: [
      'SaaS con producto self-service, pricing dinámico o onboarding dentro del sitio',
      'Consultorías sin casos de uso, verticales o promesa de valor definida',
    ],
    screenshot: '/templates/consultor-data-ai.png',
    demoUrl: 'https://example.com/templates/consultor-data-ai',
    price: {
      amountARS: 280000,
      currency: 'ARS',
      kind: 'from',
    },
    deliveryDays: {
      min: 7,
      max: 14,
    },
    includedSections: [
      'Hero con propuesta B2B',
      'Problemas que resuelve',
      'Servicios o paquetes de consultoría',
      'Casos de uso o resultados esperados',
      'Proceso de trabajo',
      'Perfil y credenciales',
      'CTA a diagnóstico',
    ],
    requiredInputs: [
      'Descripción de servicios principales',
      'Perfil del consultor o equipo',
      'Sectores o clientes objetivo',
      'Casos de uso o ejemplos permitidos',
      'Datos de contacto y agenda',
      'Referencias visuales o tono de marca',
    ],
    status: 'active',
    featured: true,
  },
  {
    slug: 'inmobiliaria-captacion-propiedades',
    title: 'Inmobiliaria y captación de propiedades',
    shortDescription:
      'Sitio para inmobiliarias o corredores con servicios, zona de trabajo, tasaciones, propiedades destacadas y contacto por WhatsApp.',
    longDescription:
      'Template para corredores inmobiliarios, inmobiliarias pequeñas o equipos comerciales que necesitan captar propietarios, mostrar zona de expertise y generar consultas. No reemplaza un portal inmobiliario: funciona como sitio de confianza, captación y contacto.',
    audience: ['local_business', 'consulting'],
    format: 'institutional',
    stack: ['nextjs', 'tailwind', 'static_export'],
    tags: ['inmobiliaria', 'propiedades', 'tasaciones', 'local', 'consultas'],
    bestFor:
      'Corredores o inmobiliarias chicas que quieren captar tasaciones, propietarios y consultas por zona.',
    primaryGoal: 'Generar consultas de tasación, venta, alquiler o propiedades destacadas.',
    complexity: 'standard',
    recommendedFor: [
      'Corredores inmobiliarios con zona de trabajo definida',
      'Inmobiliarias pequeñas que necesitan presencia profesional',
      'Equipos que quieren captar propietarios sin desarrollar un portal completo',
    ],
    notIdealFor: [
      'Portales con miles de propiedades, filtros avanzados o carga dinámica de inventario',
      'Operaciones sin matrícula, zona o propuesta comercial definida',
    ],
    screenshot: '/templates/inmobiliaria-captacion-propiedades.png',
    demoUrl: 'https://example.com/templates/inmobiliaria-captacion-propiedades',
    price: {
      amountARS: 280000,
      currency: 'ARS',
      kind: 'from',
    },
    deliveryDays: {
      min: 7,
      max: 14,
    },
    includedSections: [
      'Hero orientado a zona o especialidad',
      'Servicios: venta, alquiler y tasación',
      'Propiedades destacadas o casos',
      'Proceso de tasación',
      'Zonas de trabajo',
      'Perfil del corredor o equipo',
      'Contacto por WhatsApp',
    ],
    requiredInputs: [
      'Nombre de inmobiliaria o corredor',
      'Matrícula si corresponde',
      'Zona principal de trabajo',
      'Servicios ofrecidos',
      'Propiedades destacadas o ejemplos',
      'Fotos e identidad visual',
      'Datos de contacto',
    ],
    status: 'active',
    featured: false,
  },
  {
    slug: 'arquitectura-interiorismo-obras',
    title: 'Arquitectura, interiorismo y obras',
    shortDescription:
      'Portfolio comercial para estudios de arquitectura, interiorismo o remodelación con proyectos, proceso y consulta inicial.',
    longDescription:
      'Template visual para arquitectos, estudios de interiorismo o equipos de obra que venden proyectos de alto valor. Prioriza imagen, portfolio, estilo, proceso de trabajo y confianza para convertir visitas en consultas por proyecto.',
    audience: ['portfolio', 'consulting'],
    format: 'portfolio',
    stack: ['nextjs', 'tailwind', 'static_export'],
    tags: ['arquitectura', 'interiorismo', 'obras', 'portfolio', 'proyectos'],
    bestFor:
      'Estudios visuales o profesionales que venden proyectos de arquitectura, interiorismo, obra o remodelación.',
    primaryGoal: 'Convertir visitas en consultas por proyecto o reunión inicial.',
    complexity: 'advanced',
    recommendedFor: [
      'Arquitectos o interioristas con fotos de proyectos terminados',
      'Estudios que necesitan mostrar estilo, proceso y servicios',
      'Servicios de remodelación u obra con ticket medio/alto',
    ],
    notIdealFor: [
      'Profesionales sin portfolio visual, fotos o proyectos para mostrar',
      'Constructoras que necesitan cotizador, catálogo técnico o gestión documental',
    ],
    screenshot: '/templates/arquitectura-interiorismo-obras.png',
    demoUrl: 'https://example.com/templates/arquitectura-interiorismo-obras',
    price: {
      amountARS: 300000,
      currency: 'ARS',
      kind: 'from',
    },
    deliveryDays: {
      min: 10,
      max: 18,
    },
    includedSections: [
      'Hero visual con estilo',
      'Servicios: diseño, obra, remodelación o dirección',
      'Portfolio de proyectos',
      'Proceso de trabajo',
      'Perfil del estudio',
      'Testimonios o clientes',
      'CTA a consulta',
    ],
    requiredInputs: [
      'Nombre del estudio o profesional',
      'Servicios principales',
      'Fotos de proyectos',
      'Descripciones breves de proyectos',
      'Bio o perfil del equipo',
      'Zona de trabajo',
      'Datos de contacto',
    ],
    status: 'active',
    featured: false,
  },
  {
    slug: 'clinica-salud-local',
    title: 'Clínica o centro de salud local',
    shortDescription:
      'Sitio institucional para clínicas, centros médicos o consultorios con especialidades, equipo, ubicación y turnos.',
    longDescription:
      'Template para organizaciones de salud locales que necesitan ordenar especialidades, profesionales, datos de atención y canales de reserva sin implementar un sistema complejo de turnos. Está pensado para funcionar con WhatsApp, teléfono o agenda externa.',
    audience: ['health', 'local_business'],
    format: 'institutional',
    stack: ['nextjs', 'tailwind', 'static_export'],
    tags: ['salud', 'clinica', 'turnos', 'local', 'institucional'],
    bestFor:
      'Centros de salud locales que necesitan explicar especialidades, ubicación y canales de turno.',
    primaryGoal: 'Ayudar a pacientes a entender la oferta y solicitar turnos por canales existentes.',
    complexity: 'advanced',
    recommendedFor: [
      'Clínicas pequeñas con especialidades y horarios definidos',
      'Consultorios con varios profesionales y ubicación física',
      'Centros que ya gestionan turnos por teléfono, WhatsApp o agenda externa',
    ],
    notIdealFor: [
      'Instituciones que necesitan historia clínica, login de pacientes o turnos nativos',
      'Equipos sin información validada de profesionales, horarios y especialidades',
    ],
    screenshot: '/templates/clinica-salud-local.png',
    demoUrl: 'https://example.com/templates/clinica-salud-local',
    price: {
      amountARS: 320000,
      currency: 'ARS',
      kind: 'from',
    },
    deliveryDays: {
      min: 10,
      max: 18,
    },
    includedSections: [
      'Hero institucional de salud',
      'Especialidades y servicios',
      'Equipo profesional',
      'Información de turnos',
      'Ubicación y horarios',
      'Coberturas o medios de atención si aplica',
      'Contacto por canales existentes',
    ],
    requiredInputs: [
      'Nombre de clínica o centro',
      'Especialidades disponibles',
      'Listado de profesionales y credenciales públicas',
      'Horarios, dirección y canales de turno',
      'Fotos del espacio o equipo',
      'Textos legales o sanitarios requeridos',
    ],
    status: 'active',
    featured: false,
  },
  {
    slug: 'restaurant-reservas-simple',
    title: 'Restaurant con reservas simples',
    shortDescription:
      'Landing para restaurantes con propuesta gastronómica, menú destacado, ubicación, horarios y reservas por WhatsApp.',
    longDescription:
      'Template para restaurantes, cafés o bares que necesitan presencia clara, fotos atractivas, menú resumido y derivación a reserva sin implementar un motor gastronómico completo. Ideal para locales que ya resuelven reservas por WhatsApp, teléfono o plataforma externa.',
    audience: ['restaurant', 'local_business'],
    format: 'landing',
    stack: ['nextjs', 'tailwind', 'static_export'],
    tags: ['restaurant', 'gastronomia', 'reservas', 'menu', 'local'],
    bestFor:
      'Locales gastronómicos que quieren mostrar propuesta, horarios, ubicación y reservas por WhatsApp.',
    primaryGoal: 'Convertir visitas en reservas o consultas rápidas sobre menú y disponibilidad.',
    complexity: 'simple',
    recommendedFor: [
      'Restaurantes, cafés o bares con carta estable y buenas fotos',
      'Locales que gestionan reservas por WhatsApp, teléfono o plataforma externa',
      'Propuestas gastronómicas que necesitan comunicar ambiente y ubicación',
    ],
    notIdealFor: [
      'Delivery con carrito, pagos online o múltiples sucursales con stock',
      'Locales sin fotos, menú actualizado ni horarios confirmados',
    ],
    screenshot: '/templates/restaurant-reservas-simple.png',
    demoUrl: 'https://example.com/templates/restaurant-reservas-simple',
    price: {
      amountARS: 220000,
      currency: 'ARS',
      kind: 'from',
    },
    deliveryDays: {
      min: 5,
      max: 10,
    },
    includedSections: [
      'Hero gastronómico con foto principal',
      'Propuesta o historia del lugar',
      'Menú destacado',
      'Galería breve',
      'Horarios y ubicación',
      'Reserva por WhatsApp o link externo',
    ],
    requiredInputs: [
      'Nombre del local y propuesta gastronómica',
      'Menú o platos destacados',
      'Fotos del espacio y comida',
      'Dirección, horarios y datos de contacto',
      'Link de reservas si existe',
      'Redes sociales activas',
    ],
    status: 'active',
    featured: false,
  },
  {
    slug: 'servicios-hogar-urgencias-local',
    title: 'Servicios del hogar y urgencias locales',
    shortDescription:
      'Landing local para plomería, electricidad, gas, mantenimiento o reparaciones con zonas de cobertura y WhatsApp directo.',
    longDescription:
      'Template para servicios locales de alta intención: mantenimiento, reparaciones, instalaciones y urgencias del hogar. Está pensado para búsquedas rápidas, confianza, zona de cobertura, fotos reales de trabajos y llamada o WhatsApp inmediato.',
    audience: ['local_business'],
    format: 'landing',
    stack: ['nextjs', 'tailwind', 'static_export'],
    tags: ['servicios', 'hogar', 'urgencias', 'mantenimiento', 'local'],
    bestFor:
      'Prestadores locales que necesitan transformar búsquedas urgentes en llamadas o mensajes por WhatsApp.',
    primaryGoal: 'Generar contactos inmediatos para presupuestos, urgencias o visitas técnicas.',
    complexity: 'simple',
    recommendedFor: [
      'Plomeros, electricistas, gasistas o técnicos habilitados',
      'Servicios de mantenimiento con zonas de cobertura claras',
      'Negocios que pueden responder rápido por WhatsApp o teléfono',
    ],
    notIdealFor: [
      'Marketplaces multi-prestador o sistemas con agenda y pagos complejos',
      'Servicios sin fotos reales, horarios o zonas de cobertura definidas',
    ],
    screenshot: '/templates/servicios-hogar-urgencias-local.png',
    demoUrl: 'https://example.com/templates/servicios-hogar-urgencias-local',
    price: {
      amountARS: 200000,
      currency: 'ARS',
      kind: 'from',
    },
    deliveryDays: {
      min: 5,
      max: 10,
    },
    includedSections: [
      'Hero con servicio y zona',
      'Servicios principales',
      'Urgencias o disponibilidad',
      'Zonas de cobertura',
      'Prueba de confianza: fotos, reseñas o matrícula',
      'Cómo pedir presupuesto',
      'CTA fijo a WhatsApp',
    ],
    requiredInputs: [
      'Nombre comercial',
      'Servicios principales',
      'Zonas de cobertura',
      'Horarios de atención',
      'WhatsApp o teléfono',
      'Fotos reales de trabajos',
      'Matrículas o habilitaciones si aplica',
    ],
    status: 'active',
    featured: false,
  },
] satisfies Template[];